module.exports = {
  updateUser: `
  mutation ($openId: String!, $unionId: String, $nickName: String, $avatarUrl: String, $gender: Int, $sessionKey: String, $formId: String,){
    data: updateUser(openId: $openId, unionId: $unionId, nickName: $nickName, avatarUrl: $avatarUrl, gender: $gender, sessionKey: $sessionKey, formId: $formId){
      unionId
      openId
      nickName
      password
      gender
      avatarUrl
      sessionKey
      registerTime
      updateTime
      formId
    }
  }`,
  selectUser: `
    query($openId: String){
      data: selectUser(openId: $openId){
        ID
        unionId
        openId
        nickName
        sessionKey
        formId
        registerTime
        updateTime
      }
    }
  `
};